spring:
  datasource:
    url: jdbc:derby:database;create=true;databaseName=madb
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: madb
    password:
    initialize: true
  jpa:
    database-platform:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false

flyway:
  locations: classpath:/db/migration
  baseline-on-migrate: true
happy3w:
  footstone:
    installsvc:
      install: db/migration/V1_0_0__baseline.sql
      uninstall: db/uninstall.sql
