spring:
  datasource:
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false

flyway:
  locations: classpath:/db/migration, /db/h2

happy3w:
  footstone:
    installsvc:
      install: db/install.sql
      uninstall: db/uninstall.sql
