spring:
  datasource:
    url: jdbc:mysql://qdm210374521.my3w.com:3306/qdm210374521_db
    username: qdm210374521
    password: db1600online
    driver-class-name:
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false

flyway:
  locations: classpath:/db/migration

happy3w:
  footstone:
    installsvc:
      install: db/install.sql
      uninstall: db/uninstall.sql
